name: container
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: node-current

    steps:
      - uses: actions/checkout@v6
      - run: |
          npm install
          npm run build
